### PR TITLE
User space limits by administrator

### PR DESCRIPTION
**Pull request by Mossuru777**
Administrator is able to limit available space per user from settings page.
Please review.

### CODE REVIEW

**Comment by changami** [comment]
```
Started GET "/admin/users" for 127.0.0.1 at 2015-08-29 11:01:43 -0700
Processing by AdminController#users as HTML
  User Load (0.3ms)  SELECT "users".* FROM "users"
  Rendered admin/users.html.erb within layouts/application (7.0ms)
Completed 500 Internal Server Error in 10ms (ActiveRecord: 0.3ms)

ActionView::Template::Error (undefined method `quota_mb' for #<User:0x007f9577227748>):
    15:     <tbody>
    16: <% @users.each do |user| %>
    17:     <%
    18:        @usage_percentage = user.space_quota == 0 ? 1 : user.space_usage / user.space_quota
    19:        @usage_html_color_red = @usage_percentage > 0.8 ? sprintf('%X', 255 * (@usage_percentage * 5 - 4)) : '00'
    20:     %>
    21:         <tr>
  app/models/user.rb:9:in `is_default_space_quota?'
  app/models/user.rb:13:in `space_quota'
  app/views/admin/users.html.erb:18:in `block in _app_views_admin_users_html_erb__3780497565729039544_70139962864300'
  app/views/admin/users.html.erb:16:in `_app_views_admin_users_html_erb__3780497565729039544_70139962864300'
```

**Comment by Mossuru777** [comment]
@changami Did you perform ```bundle exec rake db:migrate``` ?

**Comment by changami** [comment]
Of course, but It doesn't work.

**Comment by changami** [comment]
Do you have any reason that it has rewritten the file directly without generating migrate files?

**Comment by Mossuru777** [comment]
It's possible to rebuild the database in 'db:reset' command because it has not yet released, and since the field has been added to the model by creating a migrate files despite the change is not so large was considered to be difficult to track.

If you think that migrate file is need, I'm going to add it.

**Comment by changami** [comment]
If there isn't an advantage or you've rewritten for only the thought, would you generate migrate file?

We should be on the rail ;)

**Comment by Mossuru777** [comment]
Ok. I'll add it.

**Comment by changami** [comment]
Thanks for making file.
But, I think there are two problems in Listing Users view.

1. The percentage of remaining capacity doesn't work.
1. We need to think about clearing flash[:alert] message.

I know that those don't have relationship each other because those are made as individual PullRequests.
Could you give me another PullRequest after that you solve No.1 problem and add the file changes?

I'll add No.2 to TaskList.

**Pull request merged**
